### ISSUE TITLE
Possible Hints for Words not Found

### ISSUE THREAD

**Issue by Shalu411** [sanskrit-lexicon/COLOGNE#10]
Namaste,
http://www.sanskrit-lexicon.uni-koeln.de/scans/PWGScan/disp2/index.php
In this page- I type "ziva" it gives output. But if I type "Siva" it says nothing. 
Not even that it gives- Issue and or message.
1. the word is wrong - (May be not found in dictionary) 
2. "try something else" (and give suggestions of spellings) 
3. "Check encoding" (and in turn open encoding page- or give link and suggest to see here)
When nothing happens it is really difficult to know if machine is on work or it is waiting for the new entry. Moreover it gets silent after giving a "working" message. That's misleading. :)

**Comment by drdhaval2785** [comment]
@funderburkjim 
Now that we are all comfortable with [edit distance](https://gist.github.com/funderburkjim/c438d0089a15676a1963) method, creating alternative suggestions are not far off I guess.

**Comment by gasyoun** [comment]
If typed `viSnu` can I get `viSNu` as a variant instead of `viS`? In the last five or so years of active usage `lookup for the longest sub-word` never helped me, never ever. Too hectic?

**Comment by drdhaval2785** [comment]
https://github.com/sanskrit-lexicon/Cologne/blob/master/enhancements/issue10/suggest.py

This works like this

`python suggest.py <inputword>'

this gives the suggestions for possible headword based on these assumptions
1. The word starts with the first letter of input word
2. The output is sorted primarily on basis of the initmach i.e. maximum letters match on the left side. e.g. initmatch("Davala","DarA")==2 because two letters on the left side match.
3. The output is shown only for the least edit-distance. e.g. if the least possible edit-distance for a given inputword is 2, then only words whose edit-distance is 2 will be shown only.

**Comment by gasyoun** [comment]
suggest.py simple, but promising.

**Comment by gasyoun** [comment]
Simples search solves only 2nd, 1st and 3rd still to be implemented.

**Comment by drdhaval2785** [comment]
simple search and hwnorm have moved ahead. Closing.

**Comment by gasyoun** [comment]
> simple search and hwnorm have moved ahead

But if they fail, there are still no valuable hints, @drdhaval2785
