### ISSUE TITLE
All Sanskrit in SLP1

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/COLOGNE#101]
I dont know where wevstand in this regard. Headwords are SLP1 for all. But what about Sanskrit items in entries? Jim may like to give overview of things as they stand now. All in one encoding will help us process all dictionaries by maybe a single script or script with small cuatomization.

This will help in both stardict generation and frontend refactoring process and unified view objective.

**Comment by gasyoun** [comment]
> Headwords are SLP1

All, @funderburkjim ?

> help in both stardict generation and frontend refactoring process

That's for sure. But as I understand if we go for unification, some things not supported in Unicode will be lost in these versions. I'm for Unicode. If only we could add some markers for the things that are doomed not the represented correctly in Unicode.

**Comment by funderburkjim** [comment]
What unification means?   

Here is how I would describe it currently.

for each dictionary X (e.g. MW, PWG), we have
* x.txt  lowest level of unification. The digitization as a text file.  Many differences in coding
   details from dictionary X to dictionary Y.
* xhw2.txt  well-unified:  page reference, headword spelling, index into line1-line2 of x.txt
   * Remaining problem:  L-numbers (headword identifier number) are not static.
* x.xml and x.dtd   This is slightly more uniform,  as all dictionaries have a few features in common:
   * common features are major elements such as 
   ```
    <Hx>
      <h><key1>..</key1><key2>..</key2>..</h>
       <body>...</body>
       <tail><L>..</L><pc>..</pc></tail>
     </Hx>
    ```
   * key1 and key2 are coded in slp1
   * within body, 
      * `<s>xx</s>`  codes text Devanagari represented as slp1
      * '<ls>xx</ls>`  codes literary references FOR some dictionaries
      * `<i>..</i>` codes italic text
      * `<b>..</b>` codes bold text
    * Otherwise, it is the wild west within body.   
       *  Various tags, little uniformity among dictionaries
       *  Various codes of IAST --- Sometimes already converted to Unicode, sometimes still in 
           AS (letter-number) coding
* Basic display for x  
   * uniformity implemented dynamically in code. 
   * source of this code is webtc/disp.php .   This program interprets the x.xml form, smoothing
     out differences in the `<body>` element so the displays for dictionary X and dictionary Y look
     similar.

So, this provides a high level overview of the dictionaries with special reference to places of
similarity and difference.

**Comment by funderburkjim** [comment]
The primary advantage of the current system, as described above, is that it leaves many decisions open until the last stage of display.  It is the display program (disp.php) that takes care of converting the
esoteric AS coding to Unicode IAST  and of interpreting the various specifics of markup, such as 
dealing with the arbitraray language tags (`<A>, <Arabic>,<g>,<gk>,<R>, etc. etc.`).

This flexibility was appropriate a few years ago, when the digitizations were less well understood than
they now are.  It let us focus on corrections, without worrying about ironing out the wrinkles of
dictionary differences.

However, now that we are wanting to do more with the dictionaries,  the differences of coding among
the dictionary digitizations are proving to be obstacles.  

The way to address this problem might be to think of pulling the uniformity supplied by disp.php
back into xml.  In otherwords, revise the construction of x.xml so that x.xml is uniform among
dictionaries.  I have not begun this. But the survey of the dtd's done by @fxru several months ago
should help.

On the other end of the problem, it is convenient to do some of the uniformizing at the level of
x.txt.  For I've begun moving some of this uniformization 'down' to the level of x.txt, notably in some conversions of AS to IAST for some dictionaries.

**Comment by funderburkjim** [comment]
@drdhaval2785   Given your interest in stardict, I suggest we choose ONE dictionary and undertake to
implement a normalization/uniformization for that dictionary.   I suggest we take one of the probably
simpler dictionaries - maybe MD.   For that dictionary we'll try to make as perfect a normalization
as we can devise for md.xml.  What say you?

**Comment by gasyoun** [comment]
> display program (disp.php) that takes care of converting the
esoteric AS coding to Unicode IAST

That means that for every UI outside Cologne it's a mess. It worked well until now, it's an obstacle indeed, but one that I would not want to be #1 priority. 

> In otherwords, revise the construction of x.xml so that x.xml is uniform among
dictionaries. I have not begun this.

That's a huge task, if @fxru is ready to help in future as well, than ok, otherwise I would still concentrate on WHAT and not HOW. @fxru is your fire still burning?

> some of this uniformization 'down' to the level of x.txt, notably in some conversions of AS to IAST for some dictionaries.

Do you remember what where the dictionaries that still had AS inside the body, @funderburkjim ?

**Comment by drdhaval2785** [comment]
>I suggest we take one of the probably
simpler dictionaries - maybe MD.

I am OK with it. I will post my requirements as and when they arise in a separate thread.

**Comment by funderburkjim** [comment]
>  I would still concentrate on WHAT and not HOW. 

The 'HOW' limits the possibilities of the feasible 'WHAT'.  

 If you want to have a garden which yields delicious summer bounty, then you have to spend time beforehand enriching the soil.   If you want to paint an old house, then you have to spend most of your time scraping the old paint off, filling in cracks, so you have a nice smooth surface for the new paint.  These homely analogies also apply to our situation.

**Comment by drdhaval2785** [comment]
All Devanagari Sanskrit is in SLP1. 
Closing this. New issue can be raised in case of missed cases.
