### ISSUE TITLE
ACC requirements for stardict

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/COLOGNE#107]
Typical line.
```
<H1><h><key1>akzaragumPa</key1><key2>akzaragumPa</key2></h><body><s>akzaragumPa</s>  ka1vya, by Sa1mara1ja Di1kshita. Ka1vyama1la1.</body><tail><L>18</L><pc>1-001,1</pc></tail></H1>
```
The web frontend shows the AS converted to IAST.
Can the same be applied in XML itself, @funderburkjim ?

**Comment by drdhaval2785** [comment]
Some improvement needed in web + xml both

अंशुमद्भेदसंग्रह vedānta, ascribed to Kaçyapa. Oppert 5875.

See ç. Also its capital version. Both need to be killed in favour of something more IASTish.

**Comment by gasyoun** [comment]
> See ç. Also its capital version. Both need to be killed in favour of something more IASTish.

For search purposes - I agree. If we can mark which sources had that `ç` before Jim killed 'em.

**Comment by funderburkjim** [comment]
This requires applying to ACC a process of conversion to modern  IAST, similar to what has been done recently with AP, AP90, MD, BUR.

IThis transformation is done at the level of xxx.txt digitization.  Since xxx.xml is derived from xxx.txt,
the transformation will be available without further effort in xxx.xml.

Will add ACC to IAST-conversion TODO list.   Ultimately, I would like this transformation to be
applied to all the dictionaries.

**Comment by funderburkjim** [comment]
> If we can mark which sources had that ç before Jim killed 'em.

This can be determined by examining each of the xxx-meta files.

**Comment by gasyoun** [comment]
> Will add ACC to IAST-conversion TODO list. Ultimately, I would like this transformation to be
applied to all the dictionaries.

Yes, it's just about time.

**Comment by drdhaval2785** [comment]
ACC is now in IAST. Closing.
