### ISSUE TITLE
acc.xml issues

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/Cologne#115]
# Typical line in acc.txt
```
<HI>{#aKaRqAnanda muni,#}¦ disciple of Akhan2d2a1nubhu1ti:
<HI1>Tarkabha1sha1praka1çavya1khya1. Taylor 1, 26.
<HI1>Tattvadi1pana Pan5capa1dika1vivaran2a (veda1nta).
<HI1>Vivaran2atattvadi1pana, a C¤: on Sureçvara's Brahma-
<>su1trabha1shyava1rttika.
```
Here H1 means that this is second level of entries (usually works of an author).

# Screenshot
![screenshot from 2017-04-09 09-19-36](https://cloud.githubusercontent.com/assets/5755132/24834515/bd3a4738-1d05-11e7-81d1-7d1ef56a3bfb.png)

# line in acc.xml
```
<H1><h><key1>aKaRqAnandamuni</key1><key2>aKaRqAnanda muni,</key2></h><body><s>aKaRqAnanda muni,</s>  disciple of Akhaṇḍānubhūti: <br/>Tarkabhāṣāprakāśavyākhyā. Taylor 1, 26. <br/>Tattvadīpana Pañcapādikāvivaraṇa (vedānta). <br/>Vivaraṇatattvadīpana, a <symbol n="C.">C.</symbol> on Sureśvara's Brahma- <br/>sūtrabhāṣyavārttika.</body><tail><L>29</L><pc>1-001,2</pc></tail></H1>
```

# Web Display 
It also doesn't capture the indent / layer information. See
![screenshot from 2017-04-09 09-15-52](https://cloud.githubusercontent.com/assets/5755132/24834494/2b27c8ca-1d05-11e7-97ac-bfa0f1b140fe.png)

# Suggestion

This information is lost in acc.xml (generically converted to `<br/>`).
@funderburkjim Can we capture it in XML itself?
Something like the following?
```
<layer n='2'>Tarkabhāṣāprakāśavyākhyā. Taylor 1, 26. </layer><br/>
<layer n='2'>Tattvadīpana Pañcapādikāvivaraṇa (vedānta). </layer><br/>
<layer n='2'>Vivaraṇatattvadīpana, a <symbol n="C.">C.</symbol> on Sureśvara's Brahma- <br/>sūtrabhāṣyavārttika</layer>
```

**Comment by drdhaval2785** [comment]
Two other observations also need disambiguation. I am not sure how. Some statistical and visual examination may help.

`<HI>--`
and
`<HI1>--`

**Comment by gasyoun** [comment]
> This information is lost in acc.xml

Indeed, it becomes just mess, pure paragraph.

**Comment by funderburkjim** [comment]
Certainly ok to think about adding markup to acc.xml.

The place to do it is in 'make_xml.py' program which makes acc.xml from acchw2.txt and acc.txt.

The 'HI' tag doesn't need to get converted -- it is the headword marker in acc.txt.
The HI1 tags could get converted to something other than the current 'br' tag.
I might prefer 
```
<div n='2'>Tarkabhāṣāprakāśavyākhyā. Taylor 1, 26. </div>
```
Only reason for preferring 'div' over 'layer' is that we have used 'div' for similar purposes in other
dictionaries.

Also, there seems no need for `<br/>` , as it is a rendering element which can be implied by `<div>`.

If such a change is made, then changes will also need to be made to:
* acc.dtd  (add div Element, and n attribute)
* the web/webtc/disp.php program which transforms from the xml of acc.xml to html.

@drdhaval2785  Did you want to try these changes, or did you want me to do so?

**Comment by gasyoun** [comment]
> Only reason for preferring 'div' over 'layer' is that we have used 'div' for similar purposes in other
dictionaries.

Makes sense.

> Also, there seems no need for <br/> , as it is a rendering element which can be implied by <div>.

Exactly.

**Comment by drdhaval2785** [comment]
I want you to do this. You know better about XMLs of various dictionaries.
So I thinj it should be easy and error free if you do it.

**Comment by funderburkjim** [comment]
OK. Putting on TODO list.

Incidentally, while beginning work on similar addition to ap.xml, I thought of one revision to our
`<div>` markup for acc.

It is easier to use just an empty tag  (`<div n="1"/>`) .  The reason is that then we don't have to worry about the **scope** of the section.  Finding the right place to put `</div>` might be problematic.

I'll start with using the long form, but if I run into difficulties in identifying the scope in acc.xml, may revert to the empty tag form.

**Comment by drdhaval2785** [comment]
In acc.txt, `<H` marks up the start of new tag before which closing tag of
previous div item can be placed safely. If you encounter anything adverse,
post the stats.

**Comment by drdhaval2785** [comment]
One more thing worth noting.
Currently `<br/>` is the same tag used at two places.
1. In place of `<>` i.e. Just a line break.
2. In place of `<HI1>` i.e. sub entry / indented entry.

See 
```
<HI>{#anuBUtiprakASa#}¦ a metrical paraphrase of twelve principal
<>Upanishads, by Sa1yan2a1ca1rya. IO. 1685. Hall p. 116.
<>K. 114. B. 4, 40. Ben. 71. 80. Pheh 12. Ra1dh
<>17. NP. I, 70. Burnell 36^b. Oppert II, 7479.
<>Rice 132.
<HI>{#anuBUtiratnamAlA#}¦ veda1nta. Burnell 92^b. Oppert II, 6186.
<HI>{#anuBUtisvarUpa#}¦ guru of Jana1rdana (Tattva1loka). Hall p. 157.
<HI>{#anuBUtisvarUpa yati#}¦
<HI1>Nya1yadi1pa1vali1 veda1nta.
<HI1>Prama1n2aratnama1la1nibandha, a C¤: on A1nandabo-
<>dha's Prama1n2aratnama1la1, veda1nta Hall p. 159.
<>L. 2869.
```
And acc.xml is 
```
<H1><h><key1>anuBUtiprakASa</key1><key2>anuBUtiprakASa</key2></h><body><s>anuBUtiprakASa</s>  a metrical paraphrase of twelve principal <br/>Upaniṣads, by Sāyaṇācārya. IO. 1685. Hall p. 116. <br/>K. 114. B. 4, 40. Ben. 71. 80. Pheh 12. Rādh <br/>17. NP. I, 70. Burnell 36^b. Oppert II, 7479. <br/>Rice 132.</body><tail><L>665</L><pc>1-017,1</pc></tail></H1>
<H1><h><key1>anuBUtiratnamAlA</key1><key2>anuBUtiratnamAlA</key2></h><body><s>anuBUtiratnamAlA</s>  vedānta. Burnell 92^b. Oppert II, 6186.</body><tail><L>666</L><pc>1-017,1</pc></tail></H1>
<H1><h><key1>anuBUtisvarUpa</key1><key2>anuBUtisvarUpa</key2></h><body><s>anuBUtisvarUpa</s>  guru of Janārdana (Tattvāloka). Hall p. 157.</body><tail><L>667</L><pc>1-017,1</pc></tail></H1>
<H1><h><key1>anuBUtisvarUpayati</key1><key2>anuBUtisvarUpa yati</key2></h><body><s>anuBUtisvarUpa yati</s> <br/>Nyāyadīpāvalī vedānta. <br/>Pramāṇaratnamālānibandha, a <symbol n="C.">C.</symbol> on Ānandabo- <br/>dha's Pramāṇaratnamālā, vedānta Hall p. 159. <br/>L. 2869.</body><tail><L>668</L><pc>1-017,1</pc></tail></H1>
```

See how <br/> is used in both senses. 
For practical purposes, e.g. in stardict generation, I would like to ignore the general line breaks, but would like to indent the line breaks depicted by `<HI1>`.

**Comment by funderburkjim** [comment]
> `<br/>` used in two senses.

Good observation.  Will alter this when I add the divs, so 'normal' line breaks distinguished from others.

Maybe will keep `<br/>` for normal line breaks, and `<div>` for the sub-headword divisions.

**Comment by funderburkjim** [comment]
> `<HI>` and '<HI1>`  what's the difference?

The `<HI>` is a 'main headword`.  It is in Devanagari bold in text.  It is the clue for determining entry headwords.

The `<HI1>` is for the 'sub-entries`.  Text is in IAST.  This is what will be trigger `<div n="2">`  markup for acc.xml.

**Comment by funderburkjim** [comment]
### `<P>` markup

There are 166 instances.
First is:
```
<HI>{#paRqitasvAmin#}¦
<HI1>Citprabha1 Paribha1shenduçekharat2i1ka1. B. 3, 10.
<P>According to Kielhorn Preface to Translation
<>of the Paribha1shenduçekhara p. XXIII, the author
<>is Brahma1nanda Sarasvati1.
```
![image](https://cloud.githubusercontent.com/assets/6393033/25684172/f4ed794e-302d-11e7-981e-bb0efe56965b.png)

Many are within 'preface' material.  

A quite different example is:
```
<HI>{#tattvacintAmaRi#}¦ ny. by Gan1geça. He quotes the gram-
<>marian Çri1kara in Çabdakhan2d2a. Pan2d2it 8, p. 4 b.--
<>AS p. 70. BC 335. CS 3, 265 (fr.). 295 (inc.). Hz. 832.
<>Peters. 5, 205 (inc.).
<P>{%Pratyaksha.%} AS p. 70. CS 3, 329 (inc.). 503.
<>Peters. 6, 183. Tod. 29. C. by Kaviratna. Rep. p. 14.
<>C. by Gada1dhara. CS 3, 395 (inc.). 499 (inc.). Hz. 831.
<>C. by Mathura1na1tha. AS p. 71. CS 3, 405. 552.
```
![image](https://cloud.githubusercontent.com/assets/6393033/25684335/ca33a1e6-302e-11e7-825d-c22d94a3cfb4.png)

It is not clear what to do with this markup.  

I'll change `<P>` to `<div n="P">...</div>`  in acc.xml,    Any html rendering suggestions?

**Comment by funderburkjim** [comment]
### `<>`C and `<>C¤` markup

There are 71 cases for `<>C¤`   and  35 for `<>C`.   

There are 6076 matches for  `<HI1>C¤:`.   

I think all of these  mean commentaries.

It is possible that we should treat the `<>`C and `<>C¤`   cases as markup errors, to be replaced by
`<HI1>`C and `<HI1>C¤:`  .  Any suggestions?

**Comment by funderburkjim** [comment]
The addition of 'div' element has been made to acc.xml, and the displays modified.
This has been done on the temporary dev server.  

Here are links to [dev server displays](http://107.170.79.53/cologne/acc/web/).

Take a look.  When others confirm these changes, I'll move them to production site at Cologne.

**Comment by gasyoun** [comment]
> I'll change <P> to <div n="P">...</div> 

Maybe `paragraph`?

`
p {
    padding-left: 2cm;
}
`

**Comment by funderburkjim** [comment]
> `<pb>`

bug  🐞  now corrected.

I also noticed the '--',  and changed display to render this as unicode EM DASH.

btw the above screen shot is for part of headword mImAMsAsUtra

![image](https://cloud.githubusercontent.com/assets/6393033/25765303/4e96260c-31ba-11e7-8930-0afc5d4b5cd2.png)

**Comment by funderburkjim** [comment]
> You speak about `<symbol n="C.">C.</symbol>`, right?

Almost.  Most of the 'C.' have been converted in acc.txt to the <symbol n="C.">C.</symbol>` form.

However those 71 and 35 cases alluded to have NOT been so changed.  

### kArakavAda  
Here is an example, under hw = kArakavAda:
```
<HI>{#kArakavAda#}¦ by Jayarāma. AK 618. 810. Whish 99, 3.
<>C. by the same. Hz. 1477.
```
![image](https://cloud.githubusercontent.com/assets/6393033/25766005/f0c5fc42-31bd-11e7-95c0-d698555b3d48.png)

Current display - notice no indentation.
![image](https://cloud.githubusercontent.com/assets/6393033/25766051/1c4382fe-31be-11e7-9a6a-998850b3f6ba.png)

### aTarvaSira upanizad
Compare to headword aTarvaSiraupanizad 
```
<HI>{#aTarvaSira upanizad#}¦ AS 4--6. BC 292. Śg. 2, 13.
<>Whish 17 a.
<HI1>C. by Bhāskararāya. Whish 17 b 3.     <<< NOTE <HI1>
<HI1>Dīpikā by Nārāyaṇa. AS p. 7.
```
![image](https://cloud.githubusercontent.com/assets/6393033/25766204/01bd277c-31bf-11e7-8325-2364f184ac03.png)

Current display:
![image](https://cloud.githubusercontent.com/assets/6393033/25766219/20cd6a64-31bf-11e7-9f88-a10896288831.png)


### coding change suggestion for kArakavAda (and the 35 others)
Code kArakavAda like aTarvaSiraupanizad 
```
<HI>{#kArakavAda#}¦ by Jayarāma. AK 618. 810. Whish 99, 3.
old:
<>C. by the same. Hz. 1477.
new:
<HI1>C. by the same. Hz. 1477.
```

**Comment by funderburkjim** [comment]
### Note on `<symbol>`
The markup `<symbol n="C.">C.</symbol>`  was introduced into acc.txt as a more explicit alternative to
the former `C¤`, and is intended to represent that `backward C + :` of the print (as in the atrismfti example shown [above](https://github.com/sanskrit-lexicon/Cologne/issues/115#issuecomment-299433614).

In 71 (I now count 75) cases, this symbol markup occurs immediately after a line break `<>` in acc.txt.

After reviewing some of these 75 cases, I have revised my opinion and think that
`<><symbol n="C.">C.</symbol>`  should not  be universally changed to
`<HI1><symbol n="C.">C.</symbol>` , since many cases are like AcAramADavIya

acc.txt
```
<HI>{#AcAramADavIya#}¦ by Mādhavācārya, the first part of his
<><symbol n="C.">C.</symbol> on the Parāśarasmṛti. Khn. 68. K. 164. Oppert     [SEE NOTE]
<>II, 7485. D 455. Quoted by Raghunandana.

NOTE:  This Commentary symbol clearly does not introduce a new division, but is part of a text section that just coincidentally occurs at the beginning of a line in the print
```
![image](https://cloud.githubusercontent.com/assets/6393033/25766838/1e957f12-31c3-11e7-8bf2-93bde19185a7.png)

However, there may be a few cases where a change from `<>` to `<HI1>` should be be made;
for instance under headword nyAyadIpAvalI:
```
<HI>{#nyAyadIpAvalI#}¦ vedānta, a refutation of the Nyāya, by
<>Ānandabodha. Rādh 6. Burnell 94^b.
<HI1><symbol n="C.">C.</symbol> Pramāṇaratnamālā or Pramāṇamālā by the same.
<>Hall p. 159. L. 1787. Rādh 6. Oudh XVIII,
<>72. Burnell 94^b.
<HI1><symbol n="CC.">CC.</symbol> Rice 156.
<HI1><symbol n="CC.">CC.</symbol> by Anubhūtisvarūpa. Hall p. 159. L. 2869.
<><symbol n="C.">C.</symbol> by Sukhaprakāśa Muni. Hall p. 206. Bik. 557.   
     PROBABLY SHOULD BE
<HI1><symbol n="C.">C.</symbol> by Sukhaprakāśa Muni. Hall p. 206. Bik. 557.  
```
![image](https://cloud.githubusercontent.com/assets/6393033/25767127/e1f25826-31c4-11e7-92ff-1cec3b727dc0.png)

**Comment by funderburkjim** [comment]
#### summary

I'll make the changes in acc.txt like `kArakavAda `.

I'll leave it to someone else to identify the cases like `nyAyadIpAvalI` that need to be changed.
The way to find these cases is to filter lines of acc.txt with regex
```
<><symbol n="C

75 cases.  
4 are <><symbol n="CC.">CC.</symbol>
71 are <><symbol n="C.">C.</symbol>
```
Then examine context to determine if `<>` should be changed to `<HI1>`.

**Comment by funderburkjim** [comment]
### cintAmaRi   obstacle and L-numbers

During examination of the cases mentioned above, the following headword error was noticed:
```
acc.txt
<HI>{#tattvacintAmaRi#}¦ or fully {#nyAyatattvacintAmaRi,#} often called
<HI>{#cintAmaRi#}¦ or merely {#maRi#} by Gaṅgeśa or Gaṅge-     <<< ERROR
<>śvara. Divided into four books: Pratyakṣa, Anu-
```
![image](https://cloud.githubusercontent.com/assets/6393033/25767587/d58ed65a-31c8-11e7-80b3-bb8dcc78e3b8.png)

While this  cintAmaRi  possibly should be classified as an Alternate headword, it definitely should not
be a *normal* headword.

One aspect of correcting this is simple:
```
20531 old <HI>{#cintAmaRi#}¦ or merely {#maRi#} by Gaṅgeśa or Gaṅge-
20531 new <>{#cintAmaRi#}¦ or merely {#maRi#} by Gaṅgeśa or Gaṅge-
```
However, if this change flows through the current system,  then we'll have a shift of L-numbers for
all the thousands of headwords following this dropped headword.  This is because in the current
system for acc,  the L-numbers are determined dynamically based on the `<HI>` sequence number in
acc.txt.

We've decided that fixed L-numbers are better than dynamic L-numbers.  This is a goal for *all* dictionaries.  But currently this goal is implemented only for SCH (recently) and MW.

We should adapt the SCH scheme to ACC before making this correction and other corrections to acc.txt.

We should think about some of the details of this before jumping into code changes.
A discussion of this is in #130.

When the details of headword coding are decided on in #130,  and have been implemented in acc.txt,
then will be the time to return and make this cintAmaRi correction.

**Comment by funderburkjim** [comment]
The changes of dev server have now been installed at cologne.  Since the main point of this issue is resolved, I'll close this issue.

The headword error noted above has not been corrected.  It will be addressed in an [issue of the CORRECTIONS repository](https://github.com/sanskrit-lexicon/CORRECTIONS/issues/352)

**Comment by gasyoun** [comment]
> Code kArakavAda like aTarvaSiraupanizad

Agree.
