### ISSUE TITLE
MD - sh issue

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/Cologne#132]
While working with MD,
md.txt now shows  `imperiṣable`.
English words have also been inadvertantly converted to IAST.

md.txt has {@....@} to identify Sanskrit text inside entry text. Can we make script more specific and avoid such collateral damage?

**Comment by funderburkjim** [comment]
> imperiṣable

There was a special section of the conversion process devoted just to 'sh'; since this character sequence
was used to code the retroflex sibilant of Sanskrit words in MD, and also occurs commonly in English words used in MD.
As a result, most English words with an 'sh' were correctly handled (not converted).  

The best way to handle the wrongly handled cases is  to introduce 'updateByLine' corrections
for them.  I find 15 matches for "imperiṣ".

Similarly, there are 16 matches for "cheriṣ"  that need correction.

We *could* examine all words in md.txt with a `ṣ`, and search for English words.  However,
since (a) there are 6000+ lines with `ṣ`, and (b) most English words have been excluded,
I would not do this.   Rather, I would just make corrections as we find them, like the two examples above.

**Comment by funderburkjim** [comment]
@drdhaval2785  I'll let you handle the above corrections on dev server, when MD is installed there.

The task will involve several steps:
1) Generate a file of corrections suitable for updateByLine.py
2) import these into the bottom of the latest manualByLine.txt for MD
3) run update_sync.sh script

Notify me so I can make similar update to Cologne.

**Comment by gasyoun** [comment]
> English words have also been inadvertantly converted to IAST.

Wow, that's bad news.

> We could examine all words in md.txt with a ṣ, and search for English words. 

Why not use a whitelist of English words? As we have a Python library for German words in old orthography.

**Comment by funderburkjim** [comment]
> Wow, that's bad news.

The original methodology essentially did the white list, although by means of applying the 'sh' change just to Sanskrit words.  The problem is that a couple of words or word fragments were incorrectly classified as Sanskrit.   So the number of errors is likely small, currently about 30 for 'imperishable' and 'cherished'.

**Comment by drdhaval2785** [comment]
https://gist.github.com/drdhaval2785/f99a587a491bedf12c7274bf9168c1bb
This implemented the code to generate the replacement for this regex.
Can be used with little change in other regexes too.

It changed the md.txt to have sh properly in my local copies of Cologne.

@funderburkjim 
1. How is such a change reflected in correctionforms.txt ?
2. The code uses python26. I keep getting `python26: command not found` errors. Can we keep it simple python ? Anyhow for python3 we use python3. At least I do.

**Comment by funderburkjim** [comment]
Your 'erish' code looks like it should generate the change lines just fine.   You should examine cases to be sure no false positives crept in.

We should change scripts to use 'python' rather than 'python26'.   It used to be that python26 was 
required on Cologne server; but now that server uses 'python'  (although the underlying version is still 2.6).  The dev server has python2.7. under 'python'.

For such 'out of band' corrections,  I just ignore correctionform.txt;   I'll usu. make a note in 'history.txt' of CORRECTIONS repository.

FYI correctionform.txt is generated from csr.tsv, and this latter is maintained as a file on Cologne server.  When user submits correction via Correction Form, that correction is converted to a tab-delimited record and is appended to the copy of csr.tsv at Cologne.   This is something that doesn't generalize well to our shadow server.

Do you know how to install the corrections generated by erish.py? [From your comment, I presume you do.]

**Comment by drdhaval2785** [comment]
Corrected and uploaded on dev server.

Time for @funderburkjim to replicate on Cologne server and close.

**Comment by funderburkjim** [comment]
Changes now installed at Cologne.

**Comment by gasyoun** [comment]
> replicate on Cologne server and close.

So it's the first of such kind? Congratulations if so.

**Comment by drdhaval2785** [comment]
Happy to report this is one of my first trials on actual implementation of
whole process of correction of a development server which is more or less
replica of Cologne server. Now I get hang of how to do stuff in Cologne
superficially.

**Comment by gasyoun** [comment]
> Now I get hang of how to do stuff in Cologne
superficially.

Hurray!

**Comment by funderburkjim** [comment]
> Now I get hang of ...

Kudos to Dhaval!
