### ISSUE TITLE
Wrong orthography for dy[uU]

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/Cologne#175]
On my Google Chrome, there seems to be some issue in rendering of the orthographic detail of 'dy[uU]'. Other cases of 'dy' letters seem OK.

How it should look
![capture](https://user-images.githubusercontent.com/5755132/29493199-a61bd4aa-85af-11e7-907c-a3456398cb8b.png)

How it looks
![capture](https://user-images.githubusercontent.com/5755132/29493195-92a61958-85af-11e7-8e23-7388f4d369d9.png)

**Comment by funderburkjim** [comment]
### The problem is Nirmala UI font
This seems to be a problem with the default font.  Consider this extract from the advanced search.
The headword is 'AdyUna' in slp1.
* `1`  This is rendered with the siddhanta font.   It is right.
*  `2` This is rendered with the default font.  On my Windows 10 system, that default is Nirmala UI font.
       It is wrong.

In other words, there is a bug with the rendering of 'dyu', 'dyU' in Nirmala UI.


![image](https://user-images.githubusercontent.com/6393033/29536540-31fc35a0-868c-11e7-8026-987852aea210.png)

### Solution
Changed relevant details of the page so siddhanta font used in `2` also:
![image](https://user-images.githubusercontent.com/6393033/29538129-586e5078-8692-11e7-9e81-0b0a5cff5f8b.png)

**Comment by funderburkjim** [comment]
### Praise for Siddhanta Font
The change above also affected the Basic Display for MW.  User `Youngsinn` sent an email saying he
really likes the Font.

I noticed a link to  a nice page for [Siddhanta Font](http://svayambhava.blogspot.com/p/siddhanta-devanagariunicode-open-type.html).

@gasyoun Thanks for alerting me to the Siddhanta font long ago.   We should aim to make it
pervasively used for Devanagari on the Cologne site.

**Comment by gasyoun** [comment]
> Thanks for alerting me to the Siddhanta font long ago.

For book printing, I have even an updated version. It's a good font for NLP.

**Comment by drdhaval2785** [comment]
Seems like we missed one case.
2,3 seem fine.
1 still uses Nirmala UI

![capture](https://user-images.githubusercontent.com/5755132/29992953-0a03b0a8-8fc6-11e7-8443-679b954b65df.png)

**Comment by drdhaval2785** [comment]
And it makes sense to make Siddhanta default in all our HTMLs.
This will obviate need to inspect further.
This font has the best ligatures. Beautiful rendering.
I printed a book with Siddhanta, and it came out really well and pleasing to read.

**Comment by gasyoun** [comment]
> I printed a book with Siddhanta, and it came out really well and pleasing to read.

I would insist it's a web font and not for printed books, still it's good, I must agree. Russian designers are best around.

**Comment by funderburkjim** [comment]
> Adyuna and siddhanta

Not sure why you show the Nirmala Font in the left pane of MW Advanced Search.  I show:
![image](https://user-images.githubusercontent.com/6393033/30082987-c25d5a6e-925a-11e7-8be0-cdacde89b1f6.png)

and, in Google Chrome, inspecting this element confirms use of Siddhanta:

![image](https://user-images.githubusercontent.com/6393033/30083047-fc4cc566-925a-11e7-971c-907ed59ed5b6.png)

Try again, and maybe empty browser cache.
