### ISSUE TITLE
pitṛ declension question

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/COLOGNE#243]
### Usual forms

The usual (acc. to Kale, Deshpande and Bucknell) declension of pitṛ  has a long vocalic r  'ṝ ' in the
accusative and genitive plural
pitṝn  and pitṝṇām.
 
### MW

(H1) [p= 626,2] : pitṛ m. (irreg. acc. pl. pitaras, MBh. ; gen. pl. ~~pitriṇām~~ pitṛṇām, BhP. ) 

(The 'ri' is a typo, now submitted as correction).

![image](https://user-images.githubusercontent.com/6393033/49261200-2d824900-f40f-11e8-825e-cb8e59df44f3.png)

### PWG
And more complete reference information in PWG:

![image](https://user-images.githubusercontent.com/6393033/49261225-4985ea80-f40f-11e8-9b3d-a10eb87c1fd7.png)

**Comment by funderburkjim** [comment]
### Questions

1) Can we track down the forms pitaraH and pitfRAm  (SLP1)  in the cited references?
    @SergeA  , can you help -- also  if you do find these, would you cite online references, if possible?

2)  Should we infer that BOTH pitaraH and pitfRAm  (SLP1) are irregular forms?
  * they do occur in established literature and hence should not be viewed as errors,
  * but the forms of Kale, etc  should be considered correct primary forms.

**Comment by SergeA** [comment]
![pitaras mbh 3 12924](https://user-images.githubusercontent.com/6435011/49288134-cd83b500-f497-11e8-94c2-72fdafc5daba.jpg)
The referenced line from MBh 3-12924 from Calcutta edition. Yes, it looks like irregular usage. The file is in my comp, I can't search for on-line version right now.

The other form of pitṛṇām instead of pitṝṇām is a common mistake, I think. And it was probably kept in one place in the edition of Bhagavata-purana, or perhaps it was a typo of that edition.

**Comment by drdhaval2785** [comment]
in hwnorm, f-ending words are traked in detail by @funderburkjim . Closing.
