### ISSUE TITLE
Text overlap

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/Cologne#244]
At https://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/simple-search/v1.0/list-0.2s.html

lead. [L=19498]

![dl](https://user-images.githubusercontent.com/80761/50740275-2bc15780-11fd-11e9-8189-d0dfcce7e9ee.PNG)

**Comment by funderburkjim** [comment]
I have been aware of this problem for some dictionaries, but thus far don't know how to fix it.

 It is caused by the way the indentation is handled.

The indentation is accomplished by adding a css `position:relative;  left:1em;` style to the `<div>` element associated with the indented section.

This does nicely indent.  But  when the `[L=...]` is tacked on to the indented section,  it does not
also get the relative styling.  Hence it overlaps.

The indented section `<div>` is just an empty div currently -- that is, the program doesn't know exactly where the subsection ends.

The only solution I see to this overlap is to have the div not be empty; i.e., to know where it ends.
But this seems hard to me.

Maybe there is a better way to handle the indentation, which I think is helpful.  But so far I don't know what that better way is.

Any suggestions?

**Comment by funderburkjim** [comment]
This has been solved for dictionaries AP and AP90.
It was previously solved for dictionaries GRA and STC.

The solution is made in apidev/dispitem.php.  The solution technique is to introduce several non-breaking spaces before the `L=xxx` text.

![image](https://user-images.githubusercontent.com/6393033/51141080-2d4ed900-1816-11e9-98af-43f478fa74fa.png)

**Comment by gasyoun** [comment]
> The only solution I see to this overlap is to have the div not be empty; i.e., to know where it ends.
But this seems hard to me.

No need for hard ways. So a CSS issue.

**Comment by funderburkjim** [comment]
Noticed similar overlap for some PWG records; and changed dispitem to add the extra spaces for PWG dictionary as well.

**Comment by gasyoun** [comment]
> Noticed similar overlap for some PWG records

Understood.

**Comment by funderburkjim** [comment]
Found similar problem with BUR, and  solved similarly.
