### ISSUE TITLE
Cologne python versions lagging behind?

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/Cologne#271]
@funderburkjim
One specific question regarding python in Cologne server.
Is it mandatory to get stuck to python 2.6.6 and 3.4.10 on Cologne?
Can't the webmasters upgrade it to the latest versions i.e. 2.7.16 and 3.7.4?

Have we ever tried to convey this to webmasters?

**Comment by drdhaval2785** [comment]
I sent a mail to the webmaster.
They have installed python2.7.15 i.e. latest python2 version.
Accessible via `python2.7` command via terminal.

**Comment by gasyoun** [comment]
> They have installed python2.7.15 i.e. latest python2 version.

After the email?

**Comment by funderburkjim** [comment]
>  I sent a mail to the webmaster.

I was going to suggest this.  Glad you went ahead and did this.

Which Python3 did you request?

One thing we need to do is upgrade our necessary python code to Python 3.  This is because support (from Python Foundation) for Python 2 is scheduled to end in 2020.

Most (maybe all) our Python code is straightforward.  The main difference is probably just in 'print'.

**Comment by drdhaval2785** [comment]
Requested python 3.7.4 i.e. latest python3.
But it is not acceded to. 

The web server RHEL6 is also slated to be End of life in 2020. So they do not want to meddle with python versions.

But they said we can compile latest python3 version on our project directory and use it locally if we want. Not systemwide installation.

**Comment by drdhaval2785** [comment]
>upgrade our necessary python code to Python3

Very important one. I will start with the necessary testings in csl-pywork repository and run with both python2.7 and python3.7. As you mentioned, most changes would be of print.

The next would be to use of {} instead of % for print statements.
The most tricky and crucial would be the unicode handling.

**Comment by funderburkjim** [comment]
>  {} instead of % for print

I think % syntax is still part of python 3 --- this is string substitution and is independent of print:
```
>>> x = 2
>>> "x == %s" %x
'x == 2'
```

I think the only usage of print in existing code is when printing to terminal,  as `print x`.
For Python3, this can change to `print(x)`   (add parentheses around the argument(s) to print.

Note that `print(x)` works in both Python2 and 3,  although the output shows parentheses in Python2,
but does not show parentheses in Python3.  This difference (in parentheses) probably is immaterial
in the sanskrit-lexicon code, since the print statement is only used for informational messages.

As to unicode,  my experiments lead me to believe that the way sanskrit-lexicon code handles
unicode *works without change* in Python3.   Python3  has probably better ways to handle Unicode,
but AFAIK we don't have to change code.

So, my suspicion currently is that the only required change will be to change the print statements by adding parentheses around the arguments.

If you discover otherwise, do mention.

**Comment by funderburkjim** [comment]
> But they said we can compile latest python3 version on our project directory and use it locally if we want. Not systemwide installation.

Let's do this as last resort.   No telling what we might encounter.   I think I have generally stuck with only very vanilla Python constructs in the sanskrit-lexicon code.

**Comment by funderburkjim** [comment]
## ignore python in correctionwork

There is a lot of Python code in the 'non-minimal' part of pywork, such as in the 'correctionwork' directory.  Since most non-minimal code will never be run again, I feel no guilt in leaving it in Python2 form.

We may want to consider making something analogous to csl-websanlexicon for the minimal pywork.
This might localize to templates the python code that needs to be upgraded to Python 3.

We also need to be sure, if possible, that the generate.py code of csl-websanlexicon works under Python3.  

I'm a little concerned about the mako code;  it seems (with your fix) to work now on server, even though server is using python2.6 and mako says it requires python2.7.   This may be because we are using a very tiny, stable portion of 'mako'.    In a way, I would prefer to use a templating system that we have more control over and that is simpler than mako, but I don't have a candidate.

**Comment by drdhaval2785** [comment]
>something analogous to csl websanlexicon for the minimal pywork.

That is already made and uploaded at https://github.com/sanskrit-lexicon/csl-pywork. Tested it. Generates minimal code well with help of mako.

**Comment by drdhaval2785** [comment]
> 'correctionwork' I feel no guilt in leaving it in Python2 form.

Me too. Only the functional code deserves the time, the precious commodity.
Today I will try to make functional code templates in https://github.com/sanskrit-lexicon/csl-pywork compliant to python3.4 i.e the python version on Cologne code.

As python3.7 is backwards compatible, whatever runs on python 3.4 will run on python3.7 also.

**Comment by drdhaval2785** [comment]
# hw.py and mako

A line in hw.py was
```python
kvparts = '<%s>%s' % (key, val)
```
or something similar.

When tried to use this as mako template, it threw an error `missing tag s`.

Changef it to the following
```python
    kvpart += '<'
    kvpart += unicode(key)
    kvpart += '>'
    kvpart += unicode(val)
```
And it works now.

Noting it here, just for reference of issues which might crop up with % usage in mako. So we will also have to minimize usage of % in our python3 compliant code.

**Comment by drdhaval2785** [comment]
# parseheadline.py

It uses xrange. 
Python2 has range and xrange.
In python3, xrange is changed to range. No function by name xrange is there.

**Comment by gasyoun** [comment]
> Since most non-minimal code will never be run again, I feel no guilt in leaving it in Python2 form.

Exactly.

> I would prefer to use a templating system that we have more control over and that is simpler than mako, but I don't have a candidate.

If Dhaval is ok with it, I would leave it, no? Still looking for a candidate?

**Comment by drdhaval2785** [comment]
I am OK with mako.
We are using only a small subset of its capabilities and it seems intuitive to me.
So no need to move away from mako.

**Comment by drdhaval2785** [comment]
@funderburkjim and @gasyoun 
Now all code in https://github.com/sanskrit-lexicon/csl-pywork/ and https://github.com/sanskrit-lexicon/csl-websanlexicon is compatible with python2 >= python2.6.6 and python3 >= 3.4.10 (cologne server versions).

There does not remain any need to upgrade python3 to python3.7 now.
Closing this issue.

**Comment by gasyoun** [comment]
> There does not remain any need to upgrade python3 to python3.7 now.

Crystal clear.
