### ISSUE TITLE
csl-websanlexicon missing web/index.php ?

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/COLOGNE#277]
@funderburkjim 
When I try to generate local versions by csl-websanlexicon repository,
I get this file missing. web/index.php
i.e. https://www.sanskrit-lexicon.uni-koeln.de/scans/SKDScan/2013/web/index.php page does not get served locally.

**Comment by funderburkjim** [comment]
I think this is a current shortcoming of websanlexicon.   i.e.,  there are no templates for web/index.php

A possible reason for this is some of the 'related material':  This is different for each dictionary, but I was
not clear on how to generate this in the templates.

Conclusion:   upgrade csl-websanlexicon so that web/index.php will be correctly generated.

**Comment by funderburkjim** [comment]
Several of the links in index.php point outside the 'web' directory.   
Suggestion:  Keep this links as absolute links to Cologne website; i.e., don't try to make these local.

**Comment by drdhaval2785** [comment]
I leave it to you to do these changes to web/index.php, so that there is no clash.

**Comment by gasyoun** [comment]
> A possible reason for this is some of the 'related material': This is different for each dictionary

So we can have them in the general config file, no need to have 33 files?

**Comment by drdhaval2785** [comment]
v02 has the index file I guess. https://github.com/sanskrit-lexicon/csl-websanlexicon/tree/master/v02/makotemplates/web 
closable, @funderburkjim?

**Comment by funderburkjim** [comment]
Yes, let's close for now.  Perhaps some questions raised have not been fully answered (such
as where the scans should reside).   But at this time,  this question is relevant to almost noone.
So let's not dwell on it.
