### ISSUE TITLE
minor change in Cologne Sanskrit-Lexicon home page

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/Cologne#76]
At Thomas Malten's request, the Cologne Sanskrit-Lexicon [home page](http://www.sanskrit-lexicon.uni-koeln.de/index.html) was slightly changed:
* An asterisk was placed by the dictionaries to indicate a funding detail of the digitization (funded by
a joint DFG-NEH grant  to Thomas Malten and Peter Scharf.
* The Apte 1957 dictionary and the Pune Dictionary appear on the home page, but with restricted
   access, namely that they are 'available on special request for research purposes'.

**Comment by gasyoun** [comment]
1) available on special request for research purposes is a good idea, but not detailed enough. I guess linking to @mailto to your email or a google docs form for filling the request would make more sense.
2) Project 2010-2013.. -> Project 2010-2013.
3) A popup tooltip explaining the meaning of the asterisk might be a solution, because it's meaning is not self evident and the explanation is rather down bellow.

**Comment by funderburkjim** [comment]
@gasyoun 
2)  Corrected.
3) Added tooltip for asterisk

1) I agree, the bureaucracy of how to make such a special request is not specified.  Will leave this fuzzy for now.

Thanks for proofreading!

**Comment by gasyoun** [comment]
Google docs form for filling the request would be best choise. 10 min to make one. And not questions remain.
A link to Malcolm's and your photo would not hurt as well in the footnote.
