### ISSUE TITLE
edit-distance method in case the word is not in dictionary

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/COLOGNE#81]
Right now, if a word is not in dictionary, the longest substring which matches headword of a given dictionary is shown.

e.g. DarziRi serach in SKD gives [this](http://www.sanskrit-lexicon.uni-koeln.de/scans/SKDScan/2013/web/webtc/indexcaller.php?key=DarziRI&input=slp1&output=SktDevaUnicode).
![capture](https://cloud.githubusercontent.com/assets/5755132/11366422/2a4e63ea-92d3-11e5-868e-100f907d1a5a.png)

What I propose is - when there is not a complete match of a word in dictionary, the headword starting with the same first letter and with least [edit-distance](https://en.wikipedia.org/wiki/Edit_distance) in that dictionary should be shown.

E.g. in the present case the least edit-distance would be of 'DarziRI'
![capture](https://cloud.githubusercontent.com/assets/5755132/11366481/7e6d1232-92d3-11e5-8ed8-60ec3ffc4730.png)

This would ensure that a person with even unsure spelling would lend somewhere nearby.

**Comment by gasyoun** [comment]
Sure it's a good idea. Any idea how to implement with little pain? Let's leave it for 2016, otherwise we will not have enough issues to deal with, Dhaval :x:

**Comment by drdhaval2785** [comment]
@gasyoun and @funderburkjim, 2016 is past. This will help users a lot. And Jim already has one python implentation of edit distance already. Shoukd not be much of a difficulty.

**Comment by funderburkjim** [comment]
Interesting idea.   I think the intent overlaps with @gasyoun 's idea of 'simple HK'  (#8)

In terms of implementation, there is one difficulty @drdhaval2785  has not considered, I think.  

If you have two words x and y, it is easy to compute the edit distance -- well-known algorithm, and we have a python implemention.  So far so good.

But suppose you have a word X and a BIG list of words Y and you want to choose the members of Y which are closest to X.   

One way to do this is to iterate over the big list Y, and compute the edit distance(y,X) for all such y,
and choose the one-or-more y with the smallest such distance.

Another way is to create from X a list of hypothetical words within a given edit distance (say 2) from X;
and then see which of these hypothetical words are in Y.
I think this is the idea of Norvig's article  on [spelling corrector](http://norvig.com/spell-correct.html).

I'm not sure if either algorithm is feasible for generating a real-time response.   

Another way, which I think may be what Google uses, is to somehow use ngrams.   

Suggestion:  Let's think about this in context of #8.   We need to prototype a UI for this.  For instance,
the Basic display you chose as example  is probably not quite the right UI.  Namely, if someone enters a mis-spelled word, rather than automatically generating a single alternate, and showing it (which is confusing to user), wouldn't it be better to show the user a list of candidates (Did you mean X Y Z...?).

The details of the UI are a bit fuzzy to me yet.  If we can get a functioning UI design, then I'll implement it at Cologne, and we can try various strategies for generating responses to misspelled words.

**Comment by funderburkjim** [comment]
Maybe a good way to start can be based on pieces present in #8.

* @juhnowski's [word_variations](https://github.com/juhnowski/word_variations)
   * duplicate this at Cologne
*  http://funderburkjim.github.io/cologneapiwork/easyspell/01/
    * duplicate this at Cologne, and integrate with word_variations above
*  The php code as [here](https://github.com/funderburkjim/funderburkjim.github.io/tree/master/cologneapiwork/easyspell/01)

Something along those lines should give us a preliminary UI to experiment with.   Our aim would
be to refine the selection process, by using Juhnowski's algorithm, and/or an algorithm based on 
edit distance [should be able to adapt the python edit-distance to php, if needed].

**Comment by gasyoun** [comment]
Norvig is rather advanced, good implementation. What about https://github.com/noahcoad/google-spell-check ? @juhnowski is lost again for a month and there seems no improvement ahead. All I hope he finishes what he started with `easyspell`.

**Comment by drdhaval2785** [comment]
Sure. Let us go on the lines of #8 to prune the list. If further refinement is needed, we will improve.

**Comment by drdhaval2785** [comment]
simple search and hwnorm1 have moved very much ahead this path. Closing.
