### ISSUE TITLE
all dictionaries pywork folders

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/COLOGNE#84]
@funderburkjim 
From whatever I could gather, the structure of cologne dictionaries are as follows
1. pwtxt (avaliable for download)
2. pwweb1 (available for download)
3. pwxml (available for download)
4. pwpywork (Not available for download from Cologne site)

Now most of the correction / coding work (except that for web display) is happening in pywork folder.
Many times the code which we work on are located at some different places and absolute paths do vary.
This causes a lot of inconvenience.

My request -
1. Let us put the pywork folders for all dictionaries in the github e.g. PWK repository here should be the actual `pwpywork` directory, rather than bits and pieces thereof. 

By this way, all the code would be possible to be reused and referred properly, and paths would be the same throughout.

In my computer,
I have 
1. pw
1.1 pwtxt
1.2 pwxml
1.3 pwweb1
1.4 pwpywork
2. pwg
2.1 pwgtxt
.
.
.

**Comment by gasyoun** [comment]
I have to admit that "bits and pieces" does not make much sense. I do not think this is a quick, nor needed tomorrow, but sure would make sense. Ultimate absolute paths would decrease unneeded work.

**Comment by funderburkjim** [comment]
Here is the structure of my local version of the PW environment:
* xampp
  * htdocs
    * cologne
       * pw
          * orig
          * pywork
          * web

This directory structure closely resembles that of the Cologne system in the 'scans directory'.

As mentioned elsewhere (#140),  there is a procedure now available at Cologne for sending
to amazon aws s3 backup zips of the 'orig', 'pywork', and 'web'  directories.  

This 'enviornment' backup has been done for all the dictionaries.

It was suggested there that this backup to s3 be done on some periodic basis (every two weeks).

I think it would be even better to do this backup for a given dictionary whenever a change (such as due to corrections) is made to that dictionary.

The current status of this regeneration is that I have a script to do it for the PW dictionary.
In coming weeks, I plan to get similar scripts for all the dictionaries.
Then, I will add running this script as a step in the correction process.  The end result will be
that the s3 backup for the environment of each dictionary will always be in sync  with Cologne.

The other side of the task is to have a script that can run on a local machine to regenerate the
environment for any dictionary by downloading the s3 backup.

In #140, I showed a script (for the Benfey dictionary) to do this.   A general script that works for
any dictionary should be possible, and I will wrute this,  assuming that others agree that this approach is a good one.

Another detail is that, using curl, it is possible to get the 'as-of-date' of one of the s3 backup files, without actually downloading the file.  Using this, there could be a script which checks whether a local system needs to download a new backup.   There may be other uses for this, such as making a listing of the 'latest' dates of all enviornment backups.

I've noticed a few differences between the php environment of the local xampp system and that at Cologne; I noticed these in the local web displays. Again assuming we go ahead with fleshing out this system,  I think these differences can be solved.

Let me know what you think.

**Comment by drdhaval2785** [comment]
Keeping Cologne and aws s3 in sync is great. Please make it part of
correction steps.
But for keeping our local copy in sync, what is painful is that we have to
download all files, even if nothing is changed in it. Around 70 MB for PW.

Can we device some way in which only the changed files are downloaded or
updated?

Some log file in download which stores the time of download and then we
curl only the files created or modified after that point in time.

**Comment by gasyoun** [comment]
Approach is good until aws s3 is alive. Until the wave it's good enough. After only our local backup will remain. Fair enough.
As per "Can we device some way in which only the changed files are downloaded or updated?" - Jim replied it's done the CURL way. But let's not hurry with it. Otherwise correction implementation might get stuck, or am I wrong, @funderburkjim ?

**Comment by funderburkjim** [comment]
@drdhaval2785   You raise two questions regarding syncing.

1.  ` even if nothing is changed in it`    --  i.e.,
  * option1 enhance  the pw_init.sh script so that it downloads everything only if the Cologne downloads require it. 
  * option2 Another way would be to add an email
notification to interested parties when the dictionary environment is regenerated at Cologne. 
  * option 3 A similar possibility would be to post a note to some Github file or issue when changes are made; then you could check this.

2. ` only the changed files are downloaded `  This seems harder to do.   I don't have a clear idea of how to do this.

I see why you raise the questions -- it's a bandwidth question. If you think one of the options mentioned under (1.) above would be useful, I can think further about it.   I am skeptical about tackling (2.).

**Comment by gasyoun** [comment]
Only option1 makes sense. Rest is almost here already. I do not think it's a bandwidth question. It's an issue of a foolish repetitive task, that could be done automatically.

**Comment by drdhaval2785** [comment]
@funderburkjim For codes, it doesn't cost much space or memory. So it is not about bandwidth, it IS about repetitive foolish works.
Option 1

**Comment by drdhaval2785** [comment]
Any update @funderburkjim?

**Comment by funderburkjim** [comment]
If it's not about bandwidth,  then the current system of s3 duplicates of Cologne pywork, web, and orig directories  (and also just the xxx.xml as a fourth s3 duplicate) should be fine. 

  I agree the S3 back system is not efficient in terms of bandwidth for syncing.  It solves my current needs well, but may not serve the needs of others.  For instance, that was why I modified it recently at Dhaval's request to get a more targeted backup of just the xml forms of the dictionaries.

My Cologne ssh connection does have 'git' command-line.   So it should be theoretically possible to
somehow sync all or part  of the Cologne system to a central Git repository, such as that at Github.   I am not eager to do the leg work needed to perfect such a  git system, since the S3 duplicates already solves the problem for my current needs.  However, I do not absolutely rule out such a git-ification of the Cologne system, if it is required.

**Comment by gasyoun** [comment]
> I do not absolutely rule out such a git-ification of the Cologne system, if it is required.

Let's test in a month or two? What do you say, Jim?

**Comment by drdhaval2785** [comment]
git-ification wil help us handle #128 along the way.
I vote for it.
Even if it is imperfect, it will be worth it. 
Version-control of git will help me understand how you change some piece of code to achieve some desired result. In the process I will understand the coding style along.

**Comment by gasyoun** [comment]
> In the process I will understand the coding style along.

That's perfect, if so.

**Comment by funderburkjim** [comment]
I thought it might be relevant for you to see the entire file-system at Cologne for one dictionary, Sch.
I generated this list using the Unix 'tree' command:
```
tree . > tree.txt
```
and moved the file [here](https://github.com/sanskrit-lexicon/SCH/blob/master/Cologne-sch-tree.txt)

**Comment by funderburkjim** [comment]
If I do a git init in a directory at Cologne, and then add some files to that repository,  how then 
would I pull the repository down to my local computer?

**Comment by drdhaval2785** [comment]
@funderburkjim, any plans for gitification now?

**Comment by drdhaval2785** [comment]
csl-pywork repo did the job. And working fine.
